### ISSUE TITLE
SAM-BA Download Location

### ISSUE THREAD

**Issue by m0wlheld** [heliflieger/a-culfw#18]
The mentioned links to download SAM-BA 2.x are outdated. The current location seems to the https://github.com/atmelcorp/sam-ba/releases . However, versions below 3.x are not available.

Please specify / update current download location.

**Comment by m0wlheld** [comment]
Or it's probably one of these: https://www.microchip.com/DevelopmentTools/ProductDetails/Atmel%20SAM-BA%20In-system%20Programmer

**Comment by heliflieger** [comment]
Which device?

**Comment by m0wlheld** [comment]
Max!Cube

**Comment by m0wlheld** [comment]
Dropped the Max!Cube. Issue no longer relevant.
