### ISSUE TITLE
Difference between nanoCUL and miniCUL

### ISSUE THREAD

**Issue by tschweitzer** [heliflieger/a-culfw#2]
Hi Björn,
can you explain a little whats the difference between nanoCUL and miniCUL? I am having a ATMEGA328P microcontroller conntected to a 433Mhz CC1101 and don't know which firmware is the right.
Many Thanks!

**Comment by CaptainRoot** [comment]
look at the makefiles:
miniCUL uses 8Mhz Clock speed, nanoCUL uses 16MHZ Clock speed

**Comment by nickma82** [comment]
@tschweitzer if this is answering your question? Then please close the issue.
Best
