### ISSUE TITLE
GT-WT-01 Sensor not working with version 1.20, but with 1.10.02

### ISSUE THREAD

**Issue by ev0lister** [heliflieger/a-culfw#4]
Hi there,

I justed discovered that with version 1.20 the GT-WT-01 sensor (Aldi Temperature/Humidity) is not working the way it should.

**Symptoms**: Sensor will only be autocreated when using "force" switch on sensor. It might be detected as "AURIOL", but "Type 1" would be correct. Normal updates are not arriving.

I just installed version **V 1.10.02** a-culfw Build: private build (unknown) nanoCUL433 (F-Band: 433MHz) and it is working as it should. Sensor autocreated and upates arriving regularly.

Other people also see this issue, e.g. http://forum.fhem.de/index.php/topic,35064.msg380027.html#msg380027

I like to assist in troubleshooting, just let me know what you need. I'm currently still struggling with the X25 debug output (dont know how to really interpret p8 / p11 messages and so on..)

Cheers
ev

**Comment by heliflieger** [comment]
Fixed with Version 01.21.00

**Comment by ev0lister** [comment]
Thanks a lot! I can confirm that it is working now.
