### ISSUE TITLE
fBand detection

### ISSUE THREAD

**Issue by nickma82** [heliflieger/a-culfw#5]
Hi, 
are the lines [link](https://github.com/heliflieger/a-culfw/blob/master/culfw/clib/fband.c#L36-L38) to detect the F-Band correct?
The Datasheet of the CC1101 says `0x0D==FREQ2, 0x0E==FREQ1,0x0F==FREQ0` which should be in the place of `0F,10 and 11` IMHO...?

This resolves my inconsistency between the CUL433 and the shown (F-Band: 868MHz), CUL V3.4.

**Comment by sharo1k** [comment]
When using absolute address (single CC), there is offset of 2 bytes. See original culfw description:

> R/W address (EEPROM) for the FS20/SlowRF Communication is = CC1101 address+2, for the FastRF Communication is CC1101 address+55. See fncollection.h for other values.

**Comment by nickma82** [comment]
I consider it correct then...
